### ISSUE TITLE
Integrate Auth0 to TLS1on1

### ISSUE THREAD

**Issue by liuyuchen777** [liuyuchen777/TLS1on1#6]
# Description

我们将使用[Auth0](https://auth0.com/)作为我们的前后端验证平台。

在前端集成Auth0后，在点击登陆按钮后用户会被redirect到Auth0的登陆界面，登陆或注册完成后会带着`user identifier`回到当前页面。我们获取access token (Bearer token/JWT token) 后用这个token touch被保护的后端API，后端API会通过Auth0的SDK来验证token的正确性和获取`user id`以便后续鉴权。

这个task需要完成前后端Auth0的继承，以及相应开发文档的写作。

# Reference
## About authentication and authorization
- [JWT token](https://jwt.io/)
## Auth0 development docs
- [Node (Express) API: Authorization](https://auth0.com/docs/quickstart/backend/nodejs/interactive)
- [node-oauth2-jwt-bearer](https://github.com/auth0/node-oauth2-jwt-bearer)
- [React: Login](https://auth0.com/docs/quickstart/spa/react/01-login)
- [React: Call an API](https://auth0.com/docs/quickstart/spa/react/02-calling-an-api)

# TODO
- [ ] Integrate with backend (express)
- [ ] Integrate with frontend (React.js)
- [ ] Write document about Auth0 setting and explaniaton for development

# Stakeholder
- @liuyuchen777
- @jackwang1219
